"""update description col name

Revision ID: b2e77138e272
Revises: 1b4bfbddb1d9
Create Date: 2023-01-23 22:25:32.897581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e77138e272'
down_revision = '1b4bfbddb1d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'])
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('projects', 'project_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'description')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_column('project_members', 'project_id')
    # ### end Alembic commands ###
